name: DEV Deploy
on:
  workflow_dispatch:
    inputs:
      Environment:
            type: choice
            description: 'Environment'
            options: 
            - dev
            - test
  
jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    name: pre-deploy
    steps:
      - name: Deploy
        run: |
          echo "This is deploy step"
  
#   child-deploy:
#     needs: pre-deploy
#     uses: ./.github/workflows/deploy-child.yml
#     with:
#       time: '*/5 * * * *'
    
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.Environment }}
    name: deploy
    needs: pre-deploy
    steps:
      - name: Deploy
        run: |
          echo "This is deploy step"
          
  post-deploy:
    runs-on: ubuntu-latest
    needs: deploy
    name: post-deploy
    steps:
      - name: Post Deploy
        run: |
          echo "This is deploy step"
