name: DEV Deploy
on:
  workflow_dispatch:
    inputs:
      Environment:
            type: choice
            description: 'Environment'
            options: 
            - dev
            - test
            - stg  
jobs:
  Version-Validation:
    runs-on: ubuntu-latest
    name: Version-Validation
    steps:
      - name: Deploy
        run: |
          echo "This is deploy step"
  User_Input_Version_Validation:
    runs-on: ubuntu-latest
    needs: Version-Validation
    name: User_Input_Version_Validation
    steps:
      - name: Deploy
        run: |
          echo "This is deploy step"  
  Artifact_Validation:
    runs-on: ubuntu-latest
    needs: User_Input_Version_Validation
    name: Artifact_Validation
    steps:
      - name: Deploy
        run: |
          echo "This is deploy step" 
  Notify_Approvers:
    runs-on: ubuntu-latest
    needs: Artifact_Validation
    name: Notify_Approvers
    steps:
      - name: Deploy
        run: |
          echo "This is deploy step" 
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.Environment }}
    name: deploy
    needs: Artifact_Validation
    steps:
      - name: Deploy
        run: |
          echo "This is deploy step"
  Post_Deployment_Artifact_Tagging:
    runs-on: ubuntu-latest
    needs: deploy
    name: Post_Deployment_Artifact_Tagging
    steps:
      - name: Post Deploy
        run: |
          echo "This is deploy step"        
  DeploymentVersionUpdator:
    runs-on: ubuntu-latest
    needs: Post_Deployment_Artifact_Tagging
    name: DeploymentVersionUpdator
    steps:
      - name: Post Deploy
        run: |
          echo "This is deploy step"
  Sent_Email:
    runs-on: ubuntu-latest
    needs: DeploymentVersionUpdator
    name: Sent_Email
    steps:
      - name: Post Deploy
        run: |
          echo "This is deploy step"
