name: Deployment
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
      Environment:
        type: choice
        required: true
        description: 'Environment'
        options: 
        - dev
        - test
        - stg  
jobs:
  Version-UserInput-Artifact-Validation:
    runs-on: ubuntu-latest
    name: Version-Validation
    steps:
      - name: Deploy
        run: |
          echo "This is deploy step"
  
  Update-DevOps-Task-ACTIVE:
    runs-on: ubuntu-latest
    needs: Version-UserInput-Artifact-Validation
    name: Update-DevOps-Task-ACTIVE
    steps:
      - name: Deploy
        run: |
          echo "This is deploy step" 
  Notify_Approvers:
    runs-on: ubuntu-latest
    needs: Update-DevOps-Task-ACTIVE
    name: Notify_Approvers
    steps:
      - name: Deploy
        run: |
          echo "This is deploy step" 
  Deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.Environment }}
    name: deploy
    needs: Notify_Approvers
    steps:
      - name: Deploy
        run: |
          echo "This is deploy step"
  Post_Deployment_Artifact_Tagging:
    runs-on: ubuntu-latest
    needs: Deploy
    name: Post_Deployment_Artifact_Tagging
    steps:
      - name: Post Deploy
        run: |
          echo "This is deploy step"        
  DeploymentVersionUpdator:
    runs-on: ubuntu-latest
    needs: Post_Deployment_Artifact_Tagging
    name: DeploymentVersionUpdator
    steps:
      - name: Post Deploy
        run: |
          echo "This is deploy step"
  Update-DevOps-Task-CLOSE:
    runs-on: ubuntu-latest
    needs: DeploymentVersionUpdator
    name: Update-DevOps-Task-CLOSE
    steps:
      - name: Deploy
        run: |
          echo "This is deploy step" 
  Sent_Email:
    runs-on: ubuntu-latest
    needs: Update-DevOps-Task-CLOSE
    name: Sent_Email
    steps:
      - name: Post Deploy
        run: |
          echo "This is deploy step"
