name: invoked

on:
#   schedule:
#     - cron: ${{ inputs.cron_schedule }}
  workflow_call:
    inputs:
      time:
        type: string
        
jobs:
  pre-deploy-child:
    runs-on: ubuntu-latest
    name: pre-deploy-child
    steps:
      - name: Deploy
        run: |
          echo ${{ inputs.time }}
