name: DEV Deploy
on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    name: deploy
    steps:
      - name: Deploy
        run: |
          echo "This is deploy step"
          
  post-deploy:
    runs-on: ubuntu-latest
    needs: deploy
    name: post-deploy
    steps:
      - name: Post Deploy
        run: |
          echo "This is deploy step"
